### ISSUE TITLE
bug: No module named 'mkdocstrings_handlers'

### ISSUE THREAD

**Issue by SamTov** [mkdocstrings/mkdocstrings#647] opened 2024-01-19 04:18 UTC
### Description of the bug
When I try to build the documentation I get the follow stack trace:

```sh
zincware) samueltovey@Samuels-MacBook-Pro-2 SwarmRL-website % mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/samueltovey/work/Repositories/SWARM/SwarmRL-website/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - pages/installation.md
ERROR   -  Error reading page 'pages/api/swarmrl.actions.actions.md': No module named 'mkdocstrings_handlers'
Traceback (most recent call last):
  File "/Users/samueltovey/miniconda3/envs/zincware/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 271, in render
    self.content = md.convert(self.markdown)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/markdown/core.py", line 357, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/markdown/blockparser.py", line 117, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/markdown/blockparser.py", line 136, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/markdown/blockparser.py", line 158, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocstrings/extension.py", line 124, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocstrings/extension.py", line 195, in _process_block
    handler = self._handlers.get_handler(handler_name, handler_config)
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/site-packages/mkdocstrings/handlers/base.py", line 459, in get_handler
    module = importlib.import_module(f"mkdocstrings_handlers.{name}")
  File "/Users/samueltovey/miniconda3/envs/zincware/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mkdocstrings_handlers'
```

### Config file:

```yml
edit_uri: blob/master/docs/
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
nav:
- Home: pages/index.md
- Introduction: pages/introduction.md
- Getting Started: pages/getting_started.md
- API Documentation:
  - swarmrl.losses.proximal_policy_loss: pages/api/swarmrl.losses.proximal_policy_loss.md
  - swarmrl.losses.loss: pages/api/swarmrl.losses.loss.md
  - swarmrl.losses.policy_gradient_loss: pages/api/swarmrl.losses.policy_gradient_loss.md
  - swarmrl.tasks.task: pages/api/swarmrl.tasks.task.md
  - swarmrl.tasks.multi_tasking: pages/api/swarmrl.tasks.multi_tasking.md
  - swarmrl.tasks.searching.species_search: pages/api/swarmrl.tasks.searching.species_search.md
  - swarmrl.tasks.searching.gradient_sensing: pages/api/swarmrl.tasks.searching.gradient_sensing.md
  - swarmrl.tasks.object_movement.rod_rotation: pages/api/swarmrl.tasks.object_movement.rod_rotation.md
  - swarmrl.force_functions.force_fn: pages/api/swarmrl.force_functions.force_fn.md
  - swarmrl.sampling_strategies.categorical_distribution: pages/api/swarmrl.sampling_strategies.categorical_distribution.md
  - swarmrl.sampling_strategies.gumbel_distribution: pages/api/swarmrl.sampling_strategies.gumbel_distribution.md
  - swarmrl.sampling_strategies.sampling_strategy: pages/api/swarmrl.sampling_strategies.sampling_strategy.md
  - swarmrl.observables.concentration_field: pages/api/swarmrl.observables.concentration_field.md
  - swarmrl.observables.subdivided_vision_cones: pages/api/swarmrl.observables.subdivided_vision_cones.md
  - swarmrl.observables.observable: pages/api/swarmrl.observables.observable.md
  - swarmrl.observables.multi_sensing: pages/api/swarmrl.observables.multi_sensing.md
  - swarmrl.observables.position: pages/api/swarmrl.observables.position.md
  - swarmrl.observables.director: pages/api/swarmrl.observables.director.md
  - swarmrl.observables.particle_sensing: pages/api/swarmrl.observables.particle_sensing.md
  - swarmrl.agents.find_point: pages/api/swarmrl.agents.find_point.md
  - swarmrl.agents.actor_critic: pages/api/swarmrl.agents.actor_critic.md
  - swarmrl.agents.classical_agent: pages/api/swarmrl.agents.classical_agent.md
  - swarmrl.agents.dummy_models: pages/api/swarmrl.agents.dummy_models.md
  - swarmrl.agents.agent: pages/api/swarmrl.agents.agent.md
  - swarmrl.agents.bechinger_models: pages/api/swarmrl.agents.bechinger_models.md
  - swarmrl.utils.colloid_utils: pages/api/swarmrl.utils.colloid_utils.md
  - swarmrl.utils.utils: pages/api/swarmrl.utils.utils.md
  - swarmrl.exploration_policies.random_exploration: pages/api/swarmrl.exploration_policies.random_exploration.md
  - swarmrl.exploration_policies.exploration_policy: pages/api/swarmrl.exploration_policies.exploration_policy.md
  - swarmrl.trainers.continuous_trainer: pages/api/swarmrl.trainers.continuous_trainer.md
  - swarmrl.trainers.episodic_trainer: pages/api/swarmrl.trainers.episodic_trainer.md
  - swarmrl.trainers.trainer: pages/api/swarmrl.trainers.trainer.md
  - swarmrl.components.swarm: pages/api/swarmrl.components.swarm.md
  - swarmrl.components.colloid: pages/api/swarmrl.components.colloid.md
  - swarmrl.networks.flax_network: pages/api/swarmrl.networks.flax_network.md
  - swarmrl.networks.network: pages/api/swarmrl.networks.network.md
  - swarmrl.value_functions.expected_returns: pages/api/swarmrl.value_functions.expected_returns.md
  - swarmrl.value_functions.generalized_advantage_estimate: pages/api/swarmrl.value_functions.generalized_advantage_estimate.md
  - swarmrl.training_routines.ensemble_submit: pages/api/swarmrl.training_routines.ensemble_submit.md
  - swarmrl.training_routines.genetic_algorithm: pages/api/swarmrl.training_routines.genetic_algorithm.md
  - swarmrl.actions.actions: pages/api/swarmrl.actions.actions.md
  - swarmrl.engine.espresso: pages/api/swarmrl.engine.espresso.md
  - swarmrl.engine.real_experiment: pages/api/swarmrl.engine.real_experiment.md
  - swarmrl.engine.engine: pages/api/swarmrl.engine.engine.md
plugins:
- search
- mkdocstrings:
      handlers:
        python: {}
repo_name: SwarmRL/SwarmRL
repo_url: https://github.com/SwarmRL/SwarmRL
site_author: Your Name or Organization
site_description: A detailed documentation of the SwarmRL project
site_name: SwarmRL Documentation
site_url: https://example.com
theme:
  favicon: assets/images/favicon.ico
  features:
  - navigation.tabs
  - navigation.instant
  - navigation.top
  logo: assets/images/logo.png
  name: material
  palette:
    accent: indigo
    primary: indigo
```

### Environment
Python 3.10
MacOS Sonoma 14.2.1 (23C71)

The source of the API is in a different folder `../SwarmRL/swarmrl` but I have played around with the src key to no avail. Any help would be grealty appreciated. Also, I have checked and rechecked that the page is installed correctly.

**Comment by tttc3** [comment] 2024-01-19 10:15
I've just had the exact same problem. I had forgot to install the python handler. The following command fixed it for me:

```bash
pip install --upgrade "mkdocstrings[python]"
```

**Comment by pawamoy** [comment] 2024-01-19 11:05
Thanks @tttc3!
@SamTov can you confirm you were missing the `mkdocstrings-python`, which can also be installed with mkdocstrings' `python` extra (as mentioned above)?

**Comment by pawamoy** [comment] 2024-01-20 12:29
I'm going to close as I'm pretty sure you're simply missing the `mkdocstrings-python` dependency. Also, duplicate of #623

**Closed** 2024-01-20 12:30 UTC
Labels: unconfirmed

**Comment by SamTov** [comment] 2024-01-21 07:20
Works great, thank you.
