### ISSUE TITLE
Recursively generate documentation for entire module without creating individual markdown files

### ISSUE THREAD

**Issue by jmkd3v** [mkdocstrings/mkdocstrings#268] opened 2021-04-11 00:52 UTC
We'd like to generate documentation for our entire module without generating a markdown file for each file. I assume this is possible, but I am having trouble doing it myself.

I have tried just adding `::: package-name` to a file - which does document all contents - but it's all in one file, which is not the ideal solution. Ideally, I'd like classes and files to be automatically placed in the sidebar.

I'm using mkdocstrings version `0.15.0`. The contents of my `mkdocs.yml` file does not seem to be relevant.

**Comment by oprypin** [comment] 2021-04-11 00:57
Take a look at https://github.com/mkdocstrings/mkdocstrings/issues/179#issuecomment-784631904
(not yet sure if the issue is duplicate or not)

**Comment by jmkd3v** [comment] 2021-04-11 02:28
> Take a look at [#179 (comment)](https://github.com/mkdocstrings/mkdocstrings/issues/179#issuecomment-784631904)
> (not yet sure if the issue is duplicate or not)

While this does partially solve the problem, it's not a solution if it can't actually add the items to the nav. I assume I can write up a script that does this and then edits the nav in the mkdocs.yml file before building, but I was hoping for a more streamlined solution.

**Comment by pawamoy** [comment] 2021-04-15 16:55
So, a user could add `literate-nav` and `gen-files` to their list of plugins to automatically generate the `SUMMARY.md` and the pages for each module. Maybe we could add such snippets in the docs :slightly_smiling_face:

**Comment by pawamoy** [comment] 2021-04-15 16:55
And yes I'd consider this issue a duplicate of #179.

**Comment by jmkd3v** [comment] 2021-04-15 17:11
I'll try to write up a snippet that uses `literate-nav` to automatically generate it.

**Comment by pawamoy** [comment] 2021-04-15 18:20
See an example in #271 :stuck_out_tongue:

**Comment by pawamoy** [comment] 2021-04-15 18:29
I'll close this in favor of the original #179 issue.

**Closed by pawamoy** 2021-04-15 18:29 UTC
Labels: question
