### ISSUE TITLE
Handler for C code

### ISSUE THREAD

**Issue by ZeroIntensity** [mkdocstrings/mkdocstrings#665] opened 2024-05-02 15:12 UTC
mkdocstrings doesn't support generating reference from C code, which is a bit limiting for Python extension modules that expose an ABI.

Hopefully this would be easy to implement? All there is to C is pretty much global variables, types, functions, and macros. I'm not sure how mkdocstrings handlers work, but I would imagine that it would be somewhat easy to implement via [pycparser](https://github.com/eliben/pycparser).

If you don't have the time, or would like to focus on another issue, I would be happy to try to implement this myself, but I would need some example code to follow on how to write a handler.

**Comment by pawamoy** [comment] 2024-05-02 17:54
Hi @ZeroIntensity, thanks for the feature request :slightly_smiling_face: 
I'll close this as duplicate of https://github.com/mkdocstrings/mkdocstrings/issues/97, lets continue the discussion over there!

**Closed by pawamoy** 2024-05-02 17:54 UTC
Labels: feature
