### ISSUE TITLE
ERROR: identifier could not be found from Cython module

### ISSUE THREAD

**Issue by nightwnvol** [mkdocstrings/mkdocstrings#603] opened 2023-08-30 15:33 UTC
**Describe the bug**
I'm trying to generate the documentation for a project containing a Cython module, but I encountered a `could not be found` error on the identifier.

**To Reproduce**
1. clone the [repo branch](https://github.com/daducci/AMICO/tree/add_readthedocs)
2. install the package (NOTE: to install from source you need to have the OpenBLAS library on your system and to set up the `site.cfg` file; in alternative you can install the package with a prebuilt wheel available [here](https://github.com/daducci/AMICO/actions/runs/6026629821) and [here for macos arm64](https://github.com/daducci/AMICO/actions/runs/6026834574))
3. run `pip install mkdocs mkdocstrings mkdocstrings[python]`
4. run `mkdocs serve -v`

**Expected behavior**
I expected to see documentation for the `StickZeppelinBall` class.

**Screenshots**
```
DEBUG   -  Loading configuration file: C:\Users\clori\Desktop\daducci_AMICO\AMICO\mkdocs.yml
DEBUG   -  Loaded theme configuration for 'readthedocs' from
           'C:\Users\clori\Desktop\daducci_AMICO\docs_new\lib\site-packages\mkdocs\themes\readthedocs\mkdocs_theme.yml':
           {'static_templates': ['404.html'], 'locale': 'en', 'include_search_page': True, 'search_index_only': False,
           'highlightjs': True, 'hljs_languages': [], 'hljs_style': 'github', 'analytics': {'gtag': None,
           'anonymize_ip': False}, 'include_homepage_in_sidebar': True, 'prev_next_buttons_location': 'bottom',
           'navigation_depth': 4, 'titles_only': False, 'sticky_navigation': True, 'collapse_navigation': True, 'logo':
           None}
DEBUG   -  Config value 'config_file_path' = 'C:\\Users\\clori\\Desktop\\daducci_AMICO\\AMICO\\mkdocs.yml'
DEBUG   -  Config value 'site_name' = 'dmri-amico'
DEBUG   -  Config value 'nav' = [{'Home': 'index.md'}, {"What's new": 'news.md'}, {'How to install': 'installation.md'},
           {'Tutorials': [{'NODDI': 'tutorials/NODDI.md'}, {'SANDI': 'tutorials/SANDI.md'}, {'ActiveAx':
           'tutorials/ACTIVEAX.md'}]}, {'Configuration': [{'Configuration parameters':
           'configuration/config_params.md'}, {'Models parameters': 'configuration/models_params.md'}, {'Angular
           resolution of the look-up tables': 'configuration/angular_resolution.md'}, {'Removing rician bias before
           fitting': 'configuration/rician_bias.md'}, {'Multithreading': 'configuration/multithreading.md'}]}, {'API
           Reference': [{'Core module': 'api_reference/core.md'}, {'Models module': 'api_reference/models.md'}]},
           {'About': [{'License': 'about/LICENSE.md'}, {'Credits': 'about/credits.md'}]}]
DEBUG   -  Config value 'pages' = None
DEBUG   -  Config value 'exclude_docs' = None
DEBUG   -  Config value 'not_in_nav' = None
DEBUG   -  Config value 'site_url' = None
DEBUG   -  Config value 'site_description' = None
DEBUG   -  Config value 'site_author' = None
DEBUG   -  Config value 'theme' = Theme(name='readthedocs',
           dirs=['C:\\Users\\clori\\Desktop\\daducci_AMICO\\docs_new\\lib\\site-packages\\mkdocs\\themes\\readthedocs',
           'C:\\Users\\clori\\Desktop\\daducci_AMICO\\docs_new\\lib\\site-packages\\mkdocs\\templates'],
           static_templates={'404.html', 'sitemap.xml'}, name='readthedocs', locale=Locale('en'),
           include_search_page=True, search_index_only=False, highlightjs=True, hljs_languages=[], hljs_style='github',
           analytics={'gtag': None, 'anonymize_ip': False}, include_homepage_in_sidebar=True,
           prev_next_buttons_location='bottom', navigation_depth=4, titles_only=False, sticky_navigation=True,
           collapse_navigation=True, logo=None)
DEBUG   -  Config value 'docs_dir' = 'C:\\Users\\clori\\Desktop\\daducci_AMICO\\AMICO\\docs'
DEBUG   -  Config value 'site_dir' = 'C:\\Users\\clori\\AppData\\Local\\Temp\\mkdocs_bm5pze5o'
DEBUG   -  Config value 'copyright' = None
DEBUG   -  Config value 'google_analytics' = None
DEBUG   -  Config value 'dev_addr' = _IpAddressValue(host='127.0.0.1', port=8000)
DEBUG   -  Config value 'use_directory_urls' = True
DEBUG   -  Config value 'repo_url' = 'https://github.com/daducci/AMICO'
DEBUG   -  Config value 'repo_name' = 'GitHub'
DEBUG   -  Config value 'edit_uri_template' = None
DEBUG   -  Config value 'edit_uri' = 'tree/master/docs/'
DEBUG   -  Config value 'extra_css' = ['css/extra.css']
DEBUG   -  Config value 'extra_javascript' = []
DEBUG   -  Config value 'extra_templates' = []
DEBUG   -  Config value 'markdown_extensions' = ['toc', 'tables', 'fenced_code', 'admonition']
DEBUG   -  Config value 'mdx_configs' = {}
DEBUG   -  Config value 'strict' = False
DEBUG   -  Config value 'remote_branch' = 'gh-pages'
DEBUG   -  Config value 'remote_name' = 'origin'
DEBUG   -  Config value 'extra' = {}
DEBUG   -  Config value 'plugins' = {'search': <mkdocs.contrib.search.SearchPlugin object at 0x000001CD62226CA0>,
           'mkdocstrings': <mkdocstrings.plugin.MkdocstringsPlugin object at 0x000001CD622268E0>}
DEBUG   -  Config value 'hooks' = {}
DEBUG   -  Config value 'watch' = []
DEBUG   -  Config value 'validation' = {'nav': {'omitted_files': 20, 'not_found': 30, 'absolute_links': 20}, 'links':
           {'not_found': 30, 'absolute_links': 20, 'unrecognized_links': 20}}
INFO    -  Building documentation...
DEBUG   -  Running 2 `config` events
DEBUG   -  mkdocstrings: Adding extension to the list
DEBUG   -  mkdocstrings: Added a subdued autorefs instance <mkdocs_autorefs.plugin.AutorefsPlugin object at
           0x000001CD62326580>
DEBUG   -  mkdocs_autorefs: Adding AutorefsExtension to the list
DEBUG   -  Running 1 `pre_build` events
INFO    -  Cleaning site directory
DEBUG   -  Looking for translations for locale 'en'
DEBUG   -  No translations found here:
           'C:\Users\clori\Desktop\daducci_AMICO\docs_new\lib\site-packages\mkdocs\contrib\search\templates\locales'
DEBUG   -  No translations found here:
           'C:\Users\clori\Desktop\daducci_AMICO\docs_new\lib\site-packages\mkdocs\templates\locales'
DEBUG   -  No translations found here:
           'C:\Users\clori\Desktop\daducci_AMICO\docs_new\lib\site-packages\mkdocs\themes\readthedocs\locales'
DEBUG   -  Reading markdown pages.
DEBUG   -  Reading: index.md
DEBUG   -  Running 1 `page_markdown` events
DEBUG   -  Running 1 `page_content` events
DEBUG   -  Reading: installation.md
DEBUG   -  Running 1 `page_markdown` events
DEBUG   -  Running 1 `page_content` events
DEBUG   -  Reading: news.md
DEBUG   -  Running 1 `page_markdown` events
DEBUG   -  Running 1 `page_content` events
DEBUG   -  Reading: about/LICENSE.md
DEBUG   -  Running 1 `page_markdown` events
DEBUG   -  Running 1 `page_content` events
DEBUG   -  Reading: about/credits.md
DEBUG   -  Running 1 `page_markdown` events
DEBUG   -  Running 1 `page_content` events
DEBUG   -  Reading: api_reference/core.md
DEBUG   -  Running 1 `page_markdown` events
DEBUG   -  mkdocstrings: Matched '::: amico.core.setup'
DEBUG   -  mkdocstrings: Using handler 'python'
DEBUG   -  mkdocstrings: Collecting data
DEBUG   -  griffe: Found amico: loading
DEBUG   -  griffe: Loading path amico\__init__.py
DEBUG   -  griffe: Loading path amico\core.py
DEBUG   -  griffe: Loading path amico\preproc.py
DEBUG   -  griffe: Loading path amico\scheme.py
DEBUG   -  griffe: Loading path amico\synthesis.py
DEBUG   -  griffe: Loading path amico\util.py
DEBUG   -  griffe: Iteration 1 finished, 0 aliases resolved, still 0 to go
DEBUG   -  mkdocstrings: Updating renderer's env
DEBUG   -  mkdocstrings: Rendering templates
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.setup
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: Matched '::: amico.core.Evaluation'
DEBUG   -  mkdocstrings: Using handler 'python'
DEBUG   -  mkdocstrings: Collecting data
DEBUG   -  mkdocstrings: Rendering templates
DEBUG   -  mkdocstrings: python\templates\material\class.html: Rendering amico.core.Evaluation
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\material\children.html: Rendering children of amico.core.Evaluation
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.__init__
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.set_config
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.get_config
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\returns.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.load_data
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.set_model
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.set_solver
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\other_parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.generate_kernels
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.load_kernels
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.fit
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\material\function.html: Rendering amico.core.Evaluation.save_results
DEBUG   -  mkdocstrings: python\templates\material\signature.html: Rendering signature
DEBUG   -  mkdocstrings: python\templates\material\docstring.html: Rendering docstring
DEBUG   -  mkdocstrings: python\templates\readthedocs\docstring\parameters.html: Rendering
DEBUG   -  mkdocstrings: Matched '::: amico.models.StickZeppelinBall'
DEBUG   -  mkdocstrings: Using handler 'python'
DEBUG   -  mkdocstrings: Collecting data
ERROR   -  mkdocstrings: amico.models.StickZeppelinBall could not be found
ERROR   -  Error reading page 'api_reference/core.md':
ERROR   -  Could not collect 'amico.models.StickZeppelinBall'

Aborted with a BuildError!
```

**Information (please complete the following information):**
- OS: [Windows x86_64]
- `mkdocs` version: [1.5.2]
- `mkdocstrings` version: [0.22.0]
- `mkdocstrings-python` version: [1.6.0]
- `griffe` version: [0.35.2]

**Comment by pawamoy** [comment] 2023-08-30 16:04
One issue with your setup (I'm not sure that's the root cause) is that your `amico` package is in the root of the repository. So when running MkDocs, Griffe searches the package and finds it in the current working directory. Since `models.pyx` is written in Cython, Griffe cannot load it.

To be able to load it, Griffe needs to actually inspect it (not parse its sources). For this, either we implement a `force_inspection` option in Griffe, or you can move your package sources in a subdirectory, typically `src`, where Griffe won't find it and will fall back to inspection.

**Comment by nightwnvol** [comment] 2023-08-30 16:36
Thank you so much @pawamoy!! Actually switch to the `src/amico` layout solved the issue. Anyway, implementing a `force_inspection` option would be great!

Thank you again for your assistence.

**Comment by pawamoy** [comment] 2023-08-30 17:30
You're welcome! I thought of another solution: Griffe could try inspecting the corresponding module when it finds a source file with `.pyx` extension. Closing, will track this in Griffe's repo :slightly_smiling_face:

**Closed by pawamoy** 2023-08-30 17:30 UTC
Labels: unconfirmed

**Comment by pawamoy** [comment] 2023-08-30 17:31
Tracked here: https://github.com/mkdocstrings/mkdocstrings/issues/603
