### ISSUE TITLE
Hot Reload Not Working in `mkdocstrings[python]==0.23.0`

### ISSUE THREAD

**Issue by nh916** [mkdocstrings/mkdocstrings#614] opened 2023-09-18 22:14 UTC
# Description
In version `mkdocstrings[python]==0.22.0`, the hot reload feature in MKDocs worked seamlessly, automatically detecting documentation changes and refreshing the view. However, after upgrading to `mkdocstrings[python]==0.23.0`, this hot reload functionality no longer operates correctly.

## Debugging Attempt
1. Used `mkdocstrings[python]==0.22.0` and hot reload worked as expected.
1. Upgraded to `mkdocstrings[python]==0.23.0`. The hot reload fails to work.
1. Downgraded back to `mkdocstrings[python]==0.22.0`. Hot reload resumes functioning correctly.

**Note:** The only change made between these steps was the package version. No other modifications were done to the code or configuration.

Here is my requirements_docs.txt file
```
mkdocs==1.5.3
mkdocs-material==9.3.1
mkdocstrings[python]==0.23.0
pymdown-extensions==10.3
jupytext==1.15.1
```

**Comment by pawamoy** [comment] 2023-09-19 09:53
I suppose you didn't move the `watch` option out of mkdocstrings configuration. This option was removed in 0.23.0 because it is now [built in MkDocs](https://www.mkdocs.org/user-guide/configuration/#watch). Closing, let me know if that's not the cause :slightly_smiling_face:

**Closed by pawamoy** 2023-09-19 09:53 UTC
Labels: unconfirmed
