### ISSUE TITLE
Duplicated attribute in dataclass

### ISSUE THREAD

**Issue by Yajo** [mkdocstrings/mkdocstrings#224] opened 2021-02-06 07:52 UTC
**Describe the bug**
The docstring of a dataclass field appears twice:

**To Reproduce**

This code triggers it:

```py
@dataclass
class Worker:
    """Copier process state manager.

    This class represents the state of a copier work, and contains methods to
    actually produce the desired work.
    """

    src_path: OptStr = None
    """String that can be resolved to a template path, be it local or remote."""
```

**Expected behavior**
Docs for `src_path` should only appear once.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/973709/107112516-1988cc00-6850-11eb-8b14-5473dd6b9cde.png)

**Information (please complete the following information):**
- OS: Linux
- Browser: Firefox
- `mkdocstrings` version: bf217e6

**Additional context**
While developing https://github.com/copier-org/copier/pull/314 (code not yet pushed).

**Comment by pawamoy** [comment] 2021-02-07 12:15
Most probably a duplicate of https://github.com/pawamoy/pytkdocs/issues/52 (though different repos). I'll it open, this way it's tracked on both repositories. Can you confirm @beanaroo's comment and tell us if it happens only for the last attribute?

**Comment by bstadlbauer** [comment] 2021-03-30 11:42
@pawamoy, can confirm, and it happens only for attributes with default values

**Comment by bstadlbauer** [comment] 2021-04-03 13:03
Fixed in pytkdocs in PR https://github.com/mkdocstrings/pytkdocs/pull/100

**Closed** 2021-04-03 13:04 UTC
Labels: unconfirmed
