### ISSUE TITLE
Support request: Implementing a VBA handler

### ISSUE THREAD

**Issue by rudolfbyker** [mkdocstrings/mkdocstrings#387] opened 2022-02-21 13:16 UTC
I'm trying to build a VBA handler that uses Google-style Python-docstrings (since there is no real standard for documenting VBA functions). My very experimental and hacky code is at https://github.com/AutoActuary/mkdocstrings-vba .

Here is my problem: When I git clone that repo, and do `pip install -e C:/path/to/mkdocstrings-vba`, it works, but if I `pip install C:/path/to/mkdocstrings-vba` it will error out with `ModuleNotFoundError: No module named 'mkdocstrings.handlers.vba'`

requirements.txt:
```
mkdocs~=1.2
mkdocs-material~=8.1
mkdocstrings-vba==0.0.3
mkdocs-gen-files~=0.3.4
mkdocs-literate-nav~=0.4.1
```

mkdocs.yml
```
site_name: Autory documentation
docs_dir: src
site_dir: dist
site_url: ""
use_directory_urls: false
theme: material

plugins:
  - mkdocstrings:
      handlers:
        vba: { }
  - gen-files:
      scripts:
        - gen_pages.py
  - literate-nav:
      nav_file: nav.md

markdown_extensions:
  - def_list
  - toc:
      permalink: true
```

**Comment by pawamoy** [comment] 2022-02-22 12:07
Hello @rudolfbyker! Nice seeing a new handler :smile: 

It seems to work on my end:

```console
% git clone https://github.com/AutoActuary/mkdocstrings-vba
Cloning into 'mkdocstrings-vba'...
remote: Enumerating objects: 152, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 152 (delta 53), reused 141 (delta 43), pack-reused 0
Receiving objects: 100% (152/152), 27.03 KiB | 1.00 MiB/s, done.
Resolving deltas: 100% (53/53), done.
% cd mkdocstrings-vba 
% python -m venv .venv
% . .venv/bin/activate
% pip install . 
Processing /media/data/dev/mkdocstrings-vba
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Collecting [...]
Successfully installed Jinja2-3.0.3 Markdown-3.3.6 MarkupSafe-2.1.0 PyYAML-6.0 click-8.0.4 ghp-import-2.0.2 griffe-0.12.6 importlib-metadata-4.11.1 mergedeep-1.3.4 mkdocs-1.2.3 mkdocs-autorefs-0.3.1 mkdocs-material-8.2.1 mkdocs-material-extensions-1.0.3 mkdocstrings-0.18.0 mkdocstrings-python-0.6.3 mkdocstrings-python-legacy-0.2.2 mkdocstrings-vba-0.0.5.dev2+g308e28e packaging-21.3 pygments-2.11.2 pymdown-extensions-9.2 pyparsing-3.0.7 python-dateutil-2.8.2 pytkdocs-0.16.0 pyyaml-env-tag-0.1 six-1.16.0 watchdog-2.1.6 zipp-3.7.0
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/media/data/dev/mkdocstrings-vba/.venv/bin/python -m pip install --upgrade pip' command.
% python
Python 3.9.9 (main, Dec  8 2021, 13:28:51) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mkdocstrings_handlers import vba
>>> vba.__file__
'/media/data/dev/mkdocstrings-vba/mkdocstrings_handlers/vba/__init__.py'
>>> vba.__path__
['/media/data/dev/mkdocstrings-vba/mkdocstrings_handlers/vba']
```

**Comment by pawamoy** [comment] 2022-02-22 12:09
I suspect there's something missing in your `setup.py` so that it can find namespace packages: https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by pawamoy** [comment] 2022-02-22 17:56
Confirmed, closing! Let me know if there's anything else!

**Comment by pawamoy** [comment] 2022-02-22 17:57
Oh, by the way, if you'd like it and when you feel ready, we can reference your handler in mkdocstrings' docs, and even add the extra so users can depend on `mkdocstrings[vba]` :slightly_smiling_face: Just let me know :slightly_smiling_face:

**Closed by pawamoy** 2022-02-22 17:56 UTC
Labels: question

**Comment by rudolfbyker** [comment] 2022-02-23 05:37
I'll let you know. I first need to figure out a few things to get this stable. Most notably, I'm still trying to figure out how to use (or abuse?) griffe in such a way that I can pass the argument types to it, when the argument types are not given in the docstring, but rather in the VBA function signature, which I parse using regex.

**Comment by pawamoy** [comment] 2022-02-23 07:10
I've documented a way here, maybe you didn't see it yet: https://mkdocstrings.github.io/griffe/usage/#using-griffe-as-a-docstring-parsing-library

**Comment by rudolfbyker** [comment] 2022-02-23 07:12
I have not seen it yet. Thanks!!

**Comment by rudolfbyker** [comment] 2022-02-23 14:55
Trying to implement this now according to https://mkdocstrings.github.io/griffe/usage/#using-griffe-as-a-docstring-parsing-library . I'm getting this error: https://github.com/mkdocstrings/griffe/issues/51

Also, another question: How can I get the path of the directory containing `mkdocs.yml` in my handler? The VBA code is loaded from text files with `.bas` extensions, and my identifiers are simply paths to those files, relative to the `mkdocs.yml` file. See https://github.com/AutoActuary/mkdocstrings-vba/blob/master/mkdocstrings_handlers/vba/handler.py#L71 and https://github.com/AutoActuary/mkdocstrings-vba/blob/7870c6f469a3568cf39da57c13c18330e6ca5c78/mkdocstrings_handlers/vba/collector.py#L44 .

**Comment by rudolfbyker** [comment] 2022-09-05 07:19
@pawamoy any ideas? I'm still stuck with the above-mentioned comment, second paragraph.

**Comment by pawamoy** [comment] 2022-09-10 15:09
Hello @rudolfbyker, sorry for the late answer, it seems I forgot to save the notification somehow.
The latest version of mkdocstrings passes the path of `mkdocs.yml` to the `get_handler` function of your package.
See how I use it in the Python handler here: https://github.com/mkdocstrings/python/blob/master/src/mkdocstrings_handlers/python/handler.py#L279

**Comment by rudolfbyker** [comment] 2023-08-22 12:07
Sorry for my even later answer! I updated the [mkdocstrings-vba](https://github.com/AutoActuary/mkdocstrings-vba) repo today, and it seems to work fine for my purposes. Would you like to review the code?

Currently I'm publishing this on our company's private pypi for internal use, but if you think it's more broadly useful, we could:
- publish it on the public pypi
- transfer the repo to you (as long as I may keep the permissions to work on the repo)
- something else?

I would love to hear your thoughts.

**Comment by pawamoy** [comment] 2023-08-22 12:19
No worries!

That's great news :rocket: 
I'd gladly accept transferring your handler to the mkdocstrings organization. You'll of course keep admin access on the repository (and will probably keep being the principal maintainer as I have no VBA experience or knowledge).

If you feel ready for it, we can even advertise the handler in mkdocstrings' docs and readme :slightly_smiling_face:
And if we do that, since you contributed a handler to mkdocstrings, I'd like to offer you access to my Insiders program :+1: Be it your own account, or a bot account from your company if you coded the handler on the company time. Let me know!

**Comment by rudolfbyker** [comment] 2023-08-22 12:59
Sure, let's do this. Do I need permissions to create a repo in your organization before I can initiate the transfer?

Regarding the insiders program, that's a nice offer, but I'm not sure that we need those specific features at the moment. However, I will continue to develop `mkdocstrings-vba` on company time as features are need or bugs are discovered. We will continue to use VBA in some of our projects for the foreseeable future.

**Comment by pawamoy** [comment] 2023-08-22 14:04
I think you don't need permission, you can simply initiate the transfer and I should get a notification to accept it.

OK, if you're interested in Insiders one day, let me know and I'll give you access :slightly_smiling_face:

**Comment by rudolfbyker** [comment] 2023-08-22 14:57
![image](https://github.com/mkdocstrings/mkdocstrings/assets/10025342/52a53a8b-5f42-4e7f-8a69-4e060218b9a8)

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

🤔

**Comment by pawamoy** [comment] 2023-08-22 15:17
OK, my bad! Will give you the necessary permissions :slightly_smiling_face:

**Comment by pawamoy** [comment] 2023-08-22 15:20
I've invited you, and members can create public/private repos, so this should be good now.

**Comment by rudolfbyker** [comment] 2023-08-22 15:24
I am honored. Feel free to rename the repo with/after the transfer.

**Comment by pawamoy** [comment] 2023-08-22 15:36
Thanks, I'll probably rename it `vba`, to be consistent with `python` and `crystal`. This will also affect the URL at which the docs are served: https://mkdocstrings.github.io/vba.

**Comment by pawamoy** [comment] 2023-08-22 18:51
Are you OK with an announcement in mkdocstrings repo telling about the transfer?

**Comment by rudolfbyker** [comment] 2023-08-23 09:26
That's 100%. Let me know if I need to contribute anything specific.
